### ISSUE TITLE
optimizer crash 

### ISSUE THREAD

**Issue by mkrompiec** [leeping/geomeTRIC#126]
For certain molecules, we are getting this error reproducibly:
Unknown Error:
Traceback (most recent call last):
  File "/sw-pmpv/sdk/anaconda-python/2020.07/envs/anaconda-2020/lib/python3.8/site-packages/geometric/optimize.py", line 1893, in main
    run_optimizer(**vars(args))
  File "/sw-pmpv/sdk/anaconda-python/2020.07/envs/anaconda-2020/lib/python3.8/site-packages/geometric/optimize.py", line 1821, in run_optimizer
    progress = Optimize(coords, M, IC, engine, dirname, params)
  File "/sw-pmpv/sdk/anaconda-python/2020.07/envs/anaconda-2020/lib/python3.8/site-packages/geometric/optimize.py", line 1331, in Optimize
    return optimizer.optimizeGeometry()
  File "/sw-pmpv/sdk/anaconda-python/2020.07/envs/anaconda-2020/lib/python3.8/site-packages/geometric/optimize.py", line 1299, in optimizeGeometry
    self.evaluateStep()
  File "/sw-pmpv/sdk/anaconda-python/2020.07/envs/anaconda-2020/lib/python3.8/site-packages/geometric/optimize.py", line 1277, in evaluateStep
    Eig1 = np.linalg.eigh(self.H)[0]
  File "<__array_function__ internals>", line 5, in eigh
  File "/sw-pmpv/sdk/anaconda-python/2020.07/envs/anaconda-2020/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 1470, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
  File "/sw-pmpv/sdk/anaconda-python/2020.07/envs/anaconda-2020/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 94, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")
numpy.linalg.LinAlgError: Eigenvalues did not converge

Unfortunately, I can't share any of the offending structures due to their confidential nature. I hope we will find a non-confidential test case soon. Anyway, do you have any hints how to fix this?

**Comment by leeping** [comment]
Hello Michal,

Thanks for sharing, this seems to be a rare error and I don't have any examples here that can reproduce it.  For these cases, one possibility is you can change the coordinate system, for example using `--coordys dlc` on the command line.  It would also be good if you could visualize the structure to make sure nothing truly unexpected is happening.

If you could write out the `self.H` variable to a file, right before the line below is called, and share the matrix with me, I may be able to reproduce the error and let you know if I can come up with a fix.  I believe the matrix does not contain any information that would allow someone to deduce the original structure.

```File "/sw-pmpv/sdk/anaconda-python/2020.07/envs/anaconda-2020/lib/python3.8/site-packages/geometric/optimize.py", line 1277, in evaluateStep
Eig1 = np.linalg.eigh(self.H)[0]
```

You can do this by editing the line indicated in the file above to the following:
```
try:
    Eig1 = np.linalg.eigh(self.H)[0]
except:
    np.save("not_converged.npy", self.H)
    raise RuntimeError("Eigenvalues did not converge")
```

Thanks,

- Lee-Ping

**Comment by jthorton** [comment]
Hi @leeping,

I am also seeing this consistently for molecules when performing 2D torsiondrives. I have attached the json input for an optimisation extracted from the 2D scan run in QCFractal. The job requires `xtb-python` and can be run via the QCEngine CLI using `qcengine run-procedure geometric geo_fail.json`. Let me know if there is anything else I can provide to help debug the issue.
[geo_fail.json.txt](https://github.com/leeping/geomeTRIC/files/7546246/geo_fail.json.txt)

**Comment by leeping** [comment]
Hi Josh,

Thanks for letting me know about this issue!  This is a late response, but
I will work on it and let you know when I find a solution.  It seems that a
problem is being encountered in diagonalizing the Hessian, and possibly a
try/except block that re-initializes the Hessian to the initial guess would
be good enough to get past that issue.

- Lee-Ping

**Comment by leeping** [comment]
@jthorton I noticed that this issue has been open for a long time now.  Is it still an issue with the latest release?
