### ISSUE TITLE
[BUG] Running Transition=True fails with geometric_run_json

### ISSUE THREAD

**Issue by coltonbh** [leeping/geomeTRIC#135]
## Overview
Running `transition=True` fails with `geometric_run_json` because [this call](https://github.com/leeping/geomeTRIC/blob/e982ad666dd9ca3fbdbcea1afd5763ae1da787bb/geometric/run_json.py#L249) (or the other similar call [here](https://github.com/leeping/geomeTRIC/blob/e982ad666dd9ca3fbdbcea1afd5763ae1da787bb/geometric/run_json.py#L260)) instantiate an `Optimizer` with `dirname=None`. When the `calcEnergyForce` [calls calc_cartesian_hessian](https://github.com/leeping/geomeTRIC/blob/e982ad666dd9ca3fbdbcea1afd5763ae1da787bb/geometric/optimize.py#L232) it passes `self.dirname` (which is None). The [first lines in calc_cartesian_hessian](https://github.com/leeping/geomeTRIC/blob/e982ad666dd9ca3fbdbcea1afd5763ae1da787bb/geometric/normal_modes.py#L72-L73) attempt to lookup a previously calculated hessian and the `os.join` call fails with `TypeError` because it cannot join `None` as a valid directory path:

```
geomeTRIC run_json error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/geometric/run_json.py", line 253, in geometric_run_json
    geometric.optimize.Optimize(coords, M, IC, engine, None, params)
  File "/opt/conda/lib/python3.9/site-packages/geometric/optimize.py", line 705, in Optimize
    return optimizer.optimizeGeometry()
  File "/opt/conda/lib/python3.9/site-packages/geometric/optimize.py", line 623, in optimizeGeometry
    self.calcEnergyForce()
  File "/opt/conda/lib/python3.9/site-packages/geometric/optimize.py", line 232, in calcEnergyForce
    self.Hx0 = calc_cartesian_hessian(self.X, self.molecule, self.engine, self.dirname, read_data=True, verbose=self.params.verbose)
  File "/opt/conda/lib/python3.9/site-packages/geometric/normal_modes.py", line 72, in calc_cartesian_hessian
    hesstxt = os.path.join(dirname, "hessian", "hessian.txt")
  File "/opt/conda/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Will create a PR to fix this...

**Comment by coltonbh** [comment]
Patching the `dirname` to a temporary directory works. The next exception raised is:
```sh
Traceback (most recent call last):
  File "/home/cbh/dev/personal/QCEngine/little_test.py", line 95, in <module>
    res = test_opt()
  File "/home/cbh/dev/personal/QCEngine/little_test.py", line 78, in test_opt
    ret = qcng.compute_procedure(input_data, optimizer, raise_error=True)
  File "/home/cbh/dev/personal/QCEngine/qcengine/compute.py", line 149, in compute_procedure
    return handle_output_metadata(output_data, metadata, raise_error=raise_error, return_dict=return_dict)
  File "/home/cbh/dev/personal/QCEngine/qcengine/util.py", line 177, in handle_output_metadata
    raise ValueError(output_fusion["error"]["error_message"])
ValueError: geomeTRIC run_json error:
Traceback (most recent call last):
  File "/home/cbh/dev/personal/geomeTRIC/geometric/run_json.py", line 251, in geometric_run_json
    geometric.optimize.Optimize(coords, M, IC, engine, dirname, params)
  File "/home/cbh/dev/personal/geomeTRIC/geometric/optimize.py", line 705, in Optimize
    return optimizer.optimizeGeometry()
  File "/home/cbh/dev/personal/geomeTRIC/geometric/optimize.py", line 623, in optimizeGeometry
    self.calcEnergyForce()
  File "/home/cbh/dev/personal/geomeTRIC/geometric/optimize.py", line 234, in calcEnergyForce
    self.frequency_analysis(self.Hx0, 'first', False)
  File "/home/cbh/dev/personal/geomeTRIC/geometric/optimize.py", line 203, in frequency_analysis
    prefix = self.params.xyzout.replace("_optim.xyz", "").replace(".xyz", "")
AttributeError: 'NoneType' object has no attribute 'replace'
```

Because there is no value for `xyzout` on the `Params` object by default.

Attempting to use `default.xyz` and the default value...
