### ISSUE TITLE
[Minor BUG]: pip installation 

### ISSUE THREAD

**Issue by lucaAyt** [leeping/geomeTRIC#184]
Hi,

Thanks for the package. Great stuff.

Wanted to draw your attention to a `pip install` issue with python 3.12 and pip 23.3.1. Got the following upon running `pip install geometric`:

```
pip install geometric
Collecting geometric
  Downloading geometric-1.0.1.tar.gz (429 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 429.1/429.1 kB 1.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /tmp/pip-install-3k1jekti/geometric_9eb4beb194884d6fb49a080a066f467c/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/home/lucaami/dev/allVenvs/comp_chem/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/lucaami/dev/allVenvs/comp_chem/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lucaami/dev/allVenvs/comp_chem/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6h83n5py/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6h83n5py/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-6h83n5py/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-6h83n5py/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 30, in <module>
        File "/tmp/pip-install-3k1jekti/geometric_9eb4beb194884d6fb49a080a066f467c/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-3k1jekti/geometric_9eb4beb194884d6fb49a080a066f467c/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-3k1jekti/geometric_9eb4beb194884d6fb49a080a066f467c/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Managed to successfully install from source so no problem but simply an FYI. 

Perhaps it's a versioning issue with PyPI as I noticed `SafeConfigParser()` is not in the latest version and #174 was only merged 3 weeks ago whereas the latest released version on PyPI (1.0.1) is from May 2023.

**Comment by leeping** [comment]
Thanks a lot for the issue report.  You're correct that there's a compatibility issue with python 3.12 in the released version.  In the next release (hopefully soon) it will be fixed.  I'll leave the issue open until that time.
