### ISSUE TITLE
Issue installing with Python 3.12

### ISSUE THREAD

**Issue by nmaskara** [leeping/geomeTRIC#187]
I tried to install the geometric package using pip install geometric through pyscf[geomopt], but got the following error message.
```
Collecting geometric>=0.9.7.2 (from pyscf[geomopt])
  Using cached geometric-1.0.1.tar.gz (429 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/setup.py", line 30, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/s3/3_6505pn269_dtgjnx_5zxxr0000gn/T/pip-install-4l9o2yyd/geometric_72cb9561ac8d4622af2dba861b9a0dcf/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I originally posted about the issue [here](https://github.com/pyscf/pyscf/issues/1980) and resolved it by downgrading to Python 3.11.

**Comment by leeping** [comment]
Thanks for the report; the current release of geomeTRIC is incompatible with Python 3.12.  I am weighing whether to make a sub-release (v1.0.2) to resolve this.

**Comment by sphuber** [comment]
Seems you already fixed the problem in https://github.com/leeping/geomeTRIC/commit/1766bc619a4c612d89673ce32a65b252db113787 . It would be great if you could make a release. This is preventing us from using Python 3.12. Bit of a shame since it is just due to a build utility and not actually due to an incompatibility with the package itself.

**Comment by leeping** [comment]
I just made a compatibility release (1.0.2).  We're not ready to make a full release yet, as we still lack some tests for new major features.  Please let me know if it resolves your installation issues.
