### ISSUE TITLE
Error with latest code

### ISSUE THREAD

**Issue by prasantapaul93** [leeping/geomeTRIC#202]
I cloned the repository and then I did git pull to get the latest code. With this latest code, I am getting the following error:
Traceback (most recent call last):
  File "/home/Prasanta/anaconda3/bin/geometric-optimize", line 33, in <module>
    sys.exit(load_entry_point('geometric==1.0.1+226.g72443c8.dirty', 'console_scripts', 'geometric-optimize')())
  File "/home/Prasanta/anaconda3/lib/python3.8/site-packages/geometric-1.0.1+226.g72443c8.dirty-py3.8.egg/geometric/optimize.py", line 1356, in main
  File "/home/Prasanta/anaconda3/lib/python3.8/site-packages/geometric-1.0.1+226.g72443c8.dirty-py3.8.egg/geometric/optimize.py", line 1150, in run_optimizer
  File "/home/Prasanta/anaconda3/lib/python3.8/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/home/Prasanta/anaconda3/lib/python3.8/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/home/Prasanta/anaconda3/lib/python3.8/configparser.py", line 960, in _getitem_
    raise KeyError(key)
KeyError: 'formatters'

how to solve this?

**Comment by leeping** [comment]
I've never seen this error before.  It is coming from the configuration of the logger.  Have you tried with Python 3.9?
